#
#Tue Mar 10 01:20:47 ART 2026
goog\:chromeOptions={args\=[--no-sandbox, --disable-dev-shm-usage, --disable-gpu, --window-size\=1920,1080, --no-sandbox, --disable-dev-shm-usage, --disable-gpu, --window-size\=1920,1080, remote-allow-origins\=*], extensions\=[]}
acceptInsecureCerts=false
browserName=chrome
